### ISSUE TITLE
Fails to parse "large" like.js files

### ISSUE THREAD

**Issue by AudunVN** [onnowhere/twitter_archive_scripts#1]
Running `get_like_data.py` on Windows 10 (x64) with Python 3.9.4 on a 72MB `like.js` file containing ~1792K lines results in the script stopping quietly after 5-10 minutes, possibly due to running out of memory.

Don't think this is a problem for most people, and it's a pretty fair input to fail on (got somewhere north of ~250K likes on Twitter). Switching to parsing like.js using UltraJSON seems to be going possibly a few orders of magnitude faster for "large" like.js files. Can make a pull request with just the UltraJSON changes if desired, my current fork is over at https://github.com/AudunVN/twitter_archive_scripts for reference.

Mostly posting this issue so people can more easily find one possible solution if they run into the same problem as I did.

PS: Thank you very much for sharing these scripts, nice work!

**Comment by onnowhere** [comment]
Thanks for letting me know and appreciate the changes! I merged them in just now
